spring:
  security:
    oauth2:
      client:
        registration:
          my-client-oidc:
            client-id: "client1"
            client-secret: "myclientsecret"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/my-client-oidc"
            scope:
              - openid
        provider:
          my-client-oidc:
            issuer-uri: http://auth-server:8000

