spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_db
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    #        ddl-auto: create
    show-sql: true


  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8000



